spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhost:8081/
          predicates:
            - Path= /cours/**
        - id: r1
          uri: http://localhost:8082/
          predicates:
            - Path= /students/**
    discovery:
      enabled: false
server:
  port: 8888
